#define PIN_FLD_OPCODE_NUM		PIN_MAKE_FLD(PIN_FLDT_STR, 11112)
#define PIN_FLD_OP_INFO           PIN_MAKE_FLD(PIN_FLDT_ARRAY, 11119)
#define PIN_FLD_OPCODE_VALUE		PIN_MAKE_FLD(PIN_FLDT_INT, 11117)
#define PIN_FLD_STATUS_VALUE              PIN_MAKE_FLD(PIN_FLDT_INT, 10022)
#define PIN_FLD_FUNCTION_NAME		PIN_MAKE_FLD(PIN_FLDT_STR, 111120)
#define PIN_FLD_SHARED_OBJECT           PIN_MAKE_FLD(PIN_FLDT_STR, 111121)

#define PCM_OP_CUST_EM                  20001
